cystadium {
  host = ${?APP_HOST}
  host = "0.0.0.0"
  port = ${?APP_PORT}
  port = 8080

  ask-timeout     = 5s
  payment-timeout = 10s
  session-ttl     = 15m
  reservation-ttl = 10m

  database {
    driver = "org.postgresql.Driver"

    db-host = "localhost"
    db-host = ${?DB_HOST}
    db-port = "5432"
    db-port = ${?DB_PORT}
    db-name = "postgres"
    db-name = ${?DB_NAME}

    url      = "jdbc:postgresql://"${cystadium.database.db-host}":"${cystadium.database.db-port}"/"${cystadium.database.db-name}
    user     = "postgres"
    user     = ${?DB_USER}
    password = ""
    password = ${?DB_PASSWORD}

    # HikariCP — pool de connexions
    connectionPool    = "HikariCP"
    numThreads        = 5
    maxConnections    = 10
    minConnections    = 2
    connectionTimeout = 30000
    idleTimeout       = 600000
  }
}

akka {
  loglevel = "INFO"
  actor {
    provider = "local"
  }
}
